---
- name: Create user accounts
  hosts: web_servers
  become: yes #Use priviledge escaltion (sudo) to create users
  vars_files:
    - passwords.yaml
  tasks:
   - name: Create user1
     user:
       name: Malik
       state: present
       groups: sudo
       shell: /bin/bash
       password: "{{ encrypted_password | b64decode }}"


   - name:
     user:
       name: Paulp
       state: present
       groups: sudo
       shell: /bin/bash
       password: "{{ encrypted_password | b64decode }}" 
